#!/bin/bash
# Managed by Puppet.
# Munin plugin for graphing Puppet Agent run times.

if [[ "$1" == "config" ]]
then
    echo 'graph_title Puppet Agent Run Time'
    echo 'graph_category puppet'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel seconds'
    echo 'time.label time'
    exit
fi

printf 'time.value '
journalctl --grep='Applied catalog' --lines=1 --output=cat _COMM=puppet | cut --delimiter=' ' --field=4
